Update check-lowercase-filenames.yml

diff --git a/.github/workflows/check-lowercase-filenames.yml b/.github/workflows/check-lowercase-filenames.yml
--- a/.github/workflows/check-lowercase-filenames.yml
+++ b/.github/workflows/check-lowercase-filenames.yml
@@ -35,6 +35,7 @@
 #               echo "All scripts passed."
 #           fi
 
+
 name: Check lowercase in filenames
 
 on:
@@ -45,29 +46,31 @@ on:
       
 jobs:
   check-lowercase-filenames:
-    runs-on: ubuntu-latest
+    runs-on: lxc
     steps:
       - name: Checkout Code
         uses: actions/checkout@v4
         
+      - name: Get changed files
+        id: changed-files
+        run: |
+          # List added or modified files in the PR that match *.sh
+          git diff --name-only --diff-filter=AM origin/main | grep -E '^(ct|install)/.*\.sh$' || true
+        shell: bash
+
       - name: Check lowercase in filenames
         shell: bash
         run: |
           set -e
-          echo "Searching for .sh files in target directories..."
-
-          # Find files in the specified paths
-          FILES=$(find ct install -type f -name "*.sh")
-
-          # Initialize error count
-          ERROR_COUNT=0
+          # Fetch changed files from the previous step
+          FILES="${{ steps.changed-files.outputs.result }}"
 
           for FILE in $FILES; do
               BASENAME=$(basename "$FILE")
               if [[ "$BASENAME" =~ ^[a-z0-9._-]+$ ]]; then
-                  echo "$BASENAME: Filename is lowercase."
+                  echo "$FILE: Check for lowercase in filename passed."
               else
-                  echo "Error: $BASENAME is not lowercase."
+                  echo "Error in $FILE. Change filename to lowercase."
                   ERROR_COUNT=$((ERROR_COUNT + 1))
               fi
           done
